name: Setup K3d
description: Setup K3d action.
author: kuritka
# see: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: grid
  color: red
inputs:
  k3d-name:
    description: "Cluster name."
    required: true
  k3d-args:
    description: "Additional arguments to k3d cluster. see: https://k3d.io/usage/commands/"
    required: false
runs:
  using: composite
  steps:
    - id: main
      shell: bash
      # You may run into issues with grabbing certificates from the API-Server
      # in case if you use default bridge network. This leads to issues, where single server exists
      # but nodes are ignored, although they are visible as docker containers. Long story short
      # `kubectl get nodes` returns single server node instead of server + agent nodes
      # see: https://k3d.io/internals/networking/#bridge-network
      # k3d action handles that and puts all clusters into bridge network
      run: |
        docker network create --driver=bridge --subnet=172.16.0.0/24 k3d-action-bridge-network
        ${{ github.action_path }}/run.sh deploy
      env:
        K3D_NAME: ${{ inputs.k3d-name }}
        K3D_ARGS: ${{ inputs.k3d-args }}
