name: Setup K3d
description: Setup K3d action.
author: kuritka
# see: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: grid
  color: red
inputs:
  k3d-name:
    description: "Cluster name."
    required: true
  k3d-args:
    description: "Additional arguments to k3d cluster. see: https://k3d.io/usage/commands/"
    required: false
  k3d-network:
    description: "Cluster network. Default value k3d-action-bridge-network"
    required: false
  k3d-cidr:
    description: "Cluster network CIDR. Default value 172.16.0.0/24 in case k3d-network is not set."
    required: false
runs:
  using: composite
  steps:
    - id: main
      shell: bash
      run: ${{ github.action_path }}/run.sh deploy
      env:
        K3D_NAME: ${{ inputs.k3d-name }}
        K3D_ARGS: ${{ inputs.k3d-args }}
        K3D_CIDR: ${{ inputs.k3d-cidr }}
        K3D_NETWORK: ${{ inputs.k3d-network }}
