name: Multicluster test

on:
  [workflow_dispatch, push]
jobs:
  k3d-inspect:
    name: Multi cluster on the common bridge network
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create-network
        run: docker network create --driver=bridge --subnet=172.16.0.0/24 custom-network
      - uses: ./
        name: "test-cluster-1 on bridge network"
        with:
          k3d-name: "test-cluster-1"
          k3d-args: >-
            -p "80:80@agent[0]"
            -p "443:443@agent[0]"
            -p "5053:53/udp@agent[0]"
            --agents 3
            --no-lb
            --network custom-network
            --wait
            --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"
      - uses: ./
        name: "test-cluster-2 on bridge network"
        with:
          k3d-name: "test-cluster-2"
          k3d-args: >-
            -p "81:80@agent[0]"
            -p "444:443@agent[0]"
            -p "5054:53/udp@agent[0]"
            --network custom-network
            --agents 3
            --no-lb
            --wait
            --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"

      - run: kubectl cluster-info --context k3d-test-cluster-1 && kubectl cluster-info --context k3d-test-cluster-2
        name: Cluster info
      - run: |
          docker ps -a
          kubectl config use-context k3d-test-cluster-1
          kubectl get nodes -o wide
        name: Nodes
      - run: docker network inspect custom-network
        name: Network
