name: Multicluster demo on isolated networks

on:
  [workflow_dispatch, push]
jobs:
  k3d-multicluster-demo:
    name: Multi cluster with default k3d-action-bridge-network
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "Test cluster 1"
        with:
          k3d-name: "test-cluster-1"
          k3d-network: "nw01"
          k3d-cidr: "172.20.0.0/24"
          k3d-args: >-
            -p "80:80@agent[0]"
            -p "443:443@agent[0]"
            -p "5053:53/udp@agent[0]"
            --agents 3
            --no-lb
            --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"

      - uses: ./
        name: "Test cluster 2"
        with:
          k3d-name: "test-cluster-2"
          k3d-network: "nw02"
          k3d-cidr: "172.20.1.0/24"
          k3d-args: >-
            -p "81:80@agent[0]"
            -p "444:443@agent[0]"
            -p "5054:53/udp@agent[0]"
            --agents 3
            --no-lb
            --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"

      - name: Cluster info
        run: kubectl cluster-info --context k3d-test-cluster-1 && kubectl cluster-info --context k3d-test-cluster-2
      - name: Nodes
        # hack, wait agents are ready.
        run: |
          docker ps -a
          kubectl config use-context k3d-test-cluster-1
          sleep 5
          kubectl get nodes -o wide
          kubectl config use-context k3d-test-cluster-2
          kubectl get nodes -o wide
      - name: Network
        run: |
          docker network inspect nw01
          docker network inspect nw02
